spring.application.name=PruebaFitclub

spring.datasource.url=jdbc:postgresql://localhost:5432/pruebafitclub
spring.datasource.username=pruebafitclub_admin
spring.datasource.password=fitclub123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=fitclub
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=debug

server.port=8080