/*
===============================================================================
PARKFLOW 360 - CREACION COMPLETA DE BASE DE DATOS (V1)
Programacion Aplicada 2026-2
Motor: PostgreSQL
Uso: ejecutar completo desde DataGrip sobre una base de datos ya creada.

BASE DOCUMENTAL:
- Guia del Estudiante - ParkFlow 360 - Modelo de Datos Completo.
- 16 tablas principales, atributos, PK, FK, UNIQUE, CHECK, nulabilidad y DER.

DECISION FISICA PARA HACER EL SCRIPT EJECUTABLE:
- Todas las PK BIGINT se implementan como GENERATED BY DEFAULT AS IDENTITY.

IMPORTANTE SOBRE DOMINIOS:
El documento fuente define algunos dominios con ejemplos y "etc.". Para que PostgreSQL
pueda aplicar CHECK reales, esta V1 fija una lista operativa minima. Si el alcance formal
cambia, los valores deben modificarse mediante una nueva migracion, no editando una V1
ya aplicada.
===============================================================================
*/

-- -----------------------------------------------------------------------------
-- 0. ESQUEMA
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS parkflow;
SET search_path TO parkflow, public;

-- -----------------------------------------------------------------------------
-- 1. USUARIO
-- -----------------------------------------------------------------------------
CREATE TABLE usuario (
    usuario_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(60)  NOT NULL,
    email            VARCHAR(160) NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    nombre_completo  VARCHAR(160) NOT NULL,
    activo           BOOLEAN      NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

COMMENT ON TABLE usuario IS 'Cuenta capaz de autenticarse y ejecutar acciones dentro de ParkFlow 360.';

-- -----------------------------------------------------------------------------
-- 2. ROL
-- -----------------------------------------------------------------------------
CREATE TABLE rol (
    rol_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(40)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  TEXT,
    activo       BOOLEAN      NOT NULL,

    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo)
);

COMMENT ON TABLE rol IS 'Funcion o conjunto de permisos asignable a usuarios.';

-- -----------------------------------------------------------------------------
-- 3. USUARIO_ROL
-- Tabla puente N:M entre USUARIO y ROL.
-- -----------------------------------------------------------------------------
CREATE TABLE usuario_rol (
    usuario_rol_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT      NOT NULL,
    rol_id          BIGINT      NOT NULL,
    asignado_at     TIMESTAMPTZ NOT NULL,
    activo          BOOLEAN     NOT NULL,

    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_rol_id),
    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id),
    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (rol_id)
        REFERENCES rol (rol_id),
    CONSTRAINT uq_usuario_rol_usuario_rol UNIQUE (usuario_id, rol_id)
);

COMMENT ON TABLE usuario_rol IS 'Tabla puente que resuelve la relacion N:M entre usuario y rol.';

-- -----------------------------------------------------------------------------
-- 4. ESTACIONAMIENTO
-- -----------------------------------------------------------------------------
CREATE TABLE estacionamiento (
    estacionamiento_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo              VARCHAR(30)  NOT NULL,
    nombre              VARCHAR(120) NOT NULL,
    direccion           VARCHAR(220) NOT NULL,
    latitud             NUMERIC(9,6),
    longitud            NUMERIC(9,6),
    activo              BOOLEAN      NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_estacionamiento PRIMARY KEY (estacionamiento_id),
    CONSTRAINT uq_estacionamiento_codigo UNIQUE (codigo)
);

COMMENT ON TABLE estacionamiento IS 'Instalacion fisica de estacionamiento administrada por el sistema.';

-- -----------------------------------------------------------------------------
-- 5. ZONA
-- El codigo es unico DENTRO de cada estacionamiento.
-- -----------------------------------------------------------------------------
CREATE TABLE zona (
    zona_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estacionamiento_id   BIGINT       NOT NULL,
    codigo               VARCHAR(20)  NOT NULL,
    nombre               VARCHAR(100) NOT NULL,
    piso                 VARCHAR(30),
    descripcion          TEXT,
    activo               BOOLEAN      NOT NULL,

    CONSTRAINT pk_zona PRIMARY KEY (zona_id),
    CONSTRAINT fk_zona_estacionamiento
        FOREIGN KEY (estacionamiento_id)
        REFERENCES estacionamiento (estacionamiento_id),
    CONSTRAINT uq_zona_estacionamiento_codigo
        UNIQUE (estacionamiento_id, codigo)
);

COMMENT ON TABLE zona IS 'Agrupa espacios dentro de un estacionamiento: piso, sector, ala o bloque.';

-- -----------------------------------------------------------------------------
-- 6. ESPACIO
-- Dominio minimo de tipo_vehiculo fijado para esta V1:
-- AUTO, MOTO, SUV, CAMIONETA, VAN, OTRO.
-- Estados definidos por el modelo:
-- DISPONIBLE, RESERVADO, OCUPADO, BLOQUEADO, FUERA_SERVICIO.
-- -----------------------------------------------------------------------------
CREATE TABLE espacio (
    espacio_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    zona_id         BIGINT      NOT NULL,
    codigo          VARCHAR(20) NOT NULL,
    tipo_vehiculo   VARCHAR(20) NOT NULL,
    estado          VARCHAR(20) NOT NULL,
    activo          BOOLEAN     NOT NULL,
    observacion     TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_espacio PRIMARY KEY (espacio_id),
    CONSTRAINT fk_espacio_zona
        FOREIGN KEY (zona_id)
        REFERENCES zona (zona_id),
    CONSTRAINT uq_espacio_zona_codigo
        UNIQUE (zona_id, codigo),
    CONSTRAINT ck_espacio_tipo_vehiculo
        CHECK (tipo_vehiculo IN ('AUTO', 'MOTO', 'SUV', 'CAMIONETA', 'VAN', 'OTRO')),
    CONSTRAINT ck_espacio_estado
        CHECK (estado IN ('DISPONIBLE', 'RESERVADO', 'OCUPADO', 'BLOQUEADO', 'FUERA_SERVICIO'))
);

COMMENT ON TABLE espacio IS 'Plaza fisica que puede estar disponible, reservada, ocupada o bloqueada.';

-- -----------------------------------------------------------------------------
-- 7. CLIENTE
-- El modelo marca numero_documento como UNIQUE segun politica y email como
-- UNIQUE segun politica. Esta V1 materializa ambas unicidades.
-- PostgreSQL permite multiples NULL en una restriccion UNIQUE, por lo que email
-- puede seguir siendo opcional.
-- -----------------------------------------------------------------------------
CREATE TABLE cliente (
    cliente_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_documento  VARCHAR(40)  NOT NULL,
    nombre_completo   VARCHAR(160) NOT NULL,
    email             VARCHAR(160),
    telefono          VARCHAR(40),
    fecha_nacimiento  DATE,
    activo            BOOLEAN      NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
    CONSTRAINT uq_cliente_numero_documento UNIQUE (numero_documento),
    CONSTRAINT uq_cliente_email UNIQUE (email)
);

COMMENT ON TABLE cliente IS 'Persona propietaria o usuaria de los vehiculos registrados.';

-- -----------------------------------------------------------------------------
-- 8. VEHICULO
-- Dominio minimo de tipo fijado para esta V1:
-- AUTO, MOTO, SUV, CAMIONETA, VAN, OTRO.
-- -----------------------------------------------------------------------------
CREATE TABLE vehiculo (
    vehiculo_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id    BIGINT      NOT NULL,
    placa         VARCHAR(20) NOT NULL,
    tipo          VARCHAR(20) NOT NULL,
    marca         VARCHAR(60),
    modelo        VARCHAR(60),
    color         VARCHAR(40),
    activo        BOOLEAN     NOT NULL,

    CONSTRAINT pk_vehiculo PRIMARY KEY (vehiculo_id),
    CONSTRAINT fk_vehiculo_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente (cliente_id),
    CONSTRAINT uq_vehiculo_placa UNIQUE (placa),
    CONSTRAINT ck_vehiculo_tipo
        CHECK (tipo IN ('AUTO', 'MOTO', 'SUV', 'CAMIONETA', 'VAN', 'OTRO'))
);

COMMENT ON TABLE vehiculo IS 'Vehiculo registrado y asociado a un cliente.';

-- -----------------------------------------------------------------------------
-- 9. TARIFA
-- Dominio minimo de unidad fijado para esta V1:
-- HORA, FRACCION, DIA, ESTANCIA, OTRO.
-- La vigencia permite vigente_hasta NULL; si existe, debe ser posterior a
-- vigente_desde.
-- -----------------------------------------------------------------------------
CREATE TABLE tarifa (
    tarifa_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estacionamiento_id    BIGINT         NOT NULL,
    nombre                VARCHAR(100)   NOT NULL,
    tipo_vehiculo         VARCHAR(20),
    monto                 NUMERIC(12,2)  NOT NULL,
    unidad                VARCHAR(20)    NOT NULL,
    vigente_desde         TIMESTAMPTZ    NOT NULL,
    vigente_hasta         TIMESTAMPTZ,
    activo                BOOLEAN        NOT NULL,

    CONSTRAINT pk_tarifa PRIMARY KEY (tarifa_id),
    CONSTRAINT fk_tarifa_estacionamiento
        FOREIGN KEY (estacionamiento_id)
        REFERENCES estacionamiento (estacionamiento_id),
    CONSTRAINT ck_tarifa_tipo_vehiculo
        CHECK (tipo_vehiculo IS NULL OR tipo_vehiculo IN ('AUTO', 'MOTO', 'SUV', 'CAMIONETA', 'VAN', 'OTRO')),
    CONSTRAINT ck_tarifa_monto
        CHECK (monto >= 0),
    CONSTRAINT ck_tarifa_unidad
        CHECK (unidad IN ('HORA', 'FRACCION', 'DIA', 'ESTANCIA', 'OTRO')),
    CONSTRAINT ck_tarifa_vigencia
        CHECK (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)
);

COMMENT ON TABLE tarifa IS 'Reglas de cobro que pueden aplicarse a una estancia.';

-- -----------------------------------------------------------------------------
-- 10. RESERVA
-- Estados definidos por el modelo:
-- PENDIENTE, CONFIRMADA, CANCELADA, VENCIDA, USADA.
-- Regla de fila adicional directamente derivada del documento:
-- una reserva CANCELADA debe registrar motivo_cancelacion.
-- NOTA: evitar solapamientos entre reservas activas requiere logica
-- transaccional/constraint avanzado y NO se resuelve con este CHECK simple.
-- -----------------------------------------------------------------------------
CREATE TABLE reserva (
    reserva_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    vehiculo_id          BIGINT      NOT NULL,
    espacio_id           BIGINT      NOT NULL,
    fecha_inicio         TIMESTAMPTZ NOT NULL,
    fecha_fin            TIMESTAMPTZ NOT NULL,
    estado               VARCHAR(20) NOT NULL,
    motivo_cancelacion   TEXT,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_reserva PRIMARY KEY (reserva_id),
    CONSTRAINT fk_reserva_vehiculo
        FOREIGN KEY (vehiculo_id)
        REFERENCES vehiculo (vehiculo_id),
    CONSTRAINT fk_reserva_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacio (espacio_id),
    CONSTRAINT ck_reserva_intervalo
        CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT ck_reserva_estado
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'VENCIDA', 'USADA')),
    CONSTRAINT ck_reserva_motivo_cancelacion
        CHECK (
            estado <> 'CANCELADA'
            OR (motivo_cancelacion IS NOT NULL AND BTRIM(motivo_cancelacion) <> '')
        )
);

COMMENT ON TABLE reserva IS 'Intencion de apartar un espacio para un vehiculo durante un intervalo.';

-- -----------------------------------------------------------------------------
-- 11. ESTANCIA
-- Relacion RESERVA 1:0..1 ESTANCIA:
-- reserva_id es opcional, pero si existe no puede repetirse.
-- Estados definidos por el modelo: ABIERTA, CERRADA, CANCELADA.
-- -----------------------------------------------------------------------------
CREATE TABLE estancia (
    estancia_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    vehiculo_id    BIGINT         NOT NULL,
    espacio_id     BIGINT         NOT NULL,
    reserva_id     BIGINT,
    tarifa_id      BIGINT,
    check_in_at    TIMESTAMPTZ    NOT NULL,
    check_out_at   TIMESTAMPTZ,
    estado         VARCHAR(20)    NOT NULL,
    monto          NUMERIC(12,2),
    created_at     TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pk_estancia PRIMARY KEY (estancia_id),
    CONSTRAINT fk_estancia_vehiculo
        FOREIGN KEY (vehiculo_id)
        REFERENCES vehiculo (vehiculo_id),
    CONSTRAINT fk_estancia_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacio (espacio_id),
    CONSTRAINT fk_estancia_reserva
        FOREIGN KEY (reserva_id)
        REFERENCES reserva (reserva_id),
    CONSTRAINT fk_estancia_tarifa
        FOREIGN KEY (tarifa_id)
        REFERENCES tarifa (tarifa_id),
    CONSTRAINT uq_estancia_reserva UNIQUE (reserva_id),
    CONSTRAINT ck_estancia_salida
        CHECK (check_out_at IS NULL OR check_out_at > check_in_at),
    CONSTRAINT ck_estancia_estado
        CHECK (estado IN ('ABIERTA', 'CERRADA', 'CANCELADA')),
    CONSTRAINT ck_estancia_monto
        CHECK (monto IS NULL OR monto >= 0)
);

COMMENT ON TABLE estancia IS 'Ingreso real de un vehiculo y ocupacion efectiva de un espacio.';

-- -----------------------------------------------------------------------------
-- 12. PAGO_OPERATIVO
-- Metodos operativos minimos fijados para esta V1:
-- EFECTIVO, QR, TARJETA, TRANSFERENCIA, OTRO.
-- Estados definidos por el modelo: PENDIENTE, CONFIRMADO, ANULADO.
-- -----------------------------------------------------------------------------
CREATE TABLE pago_operativo (
    pago_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estancia_id   BIGINT         NOT NULL,
    monto         NUMERIC(12,2)  NOT NULL,
    metodo        VARCHAR(30)    NOT NULL,
    referencia    VARCHAR(100),
    paid_at       TIMESTAMPTZ    NOT NULL,
    estado        VARCHAR(20)    NOT NULL,

    CONSTRAINT pk_pago_operativo PRIMARY KEY (pago_id),
    CONSTRAINT fk_pago_operativo_estancia
        FOREIGN KEY (estancia_id)
        REFERENCES estancia (estancia_id),
    CONSTRAINT ck_pago_operativo_monto
        CHECK (monto >= 0),
    CONSTRAINT ck_pago_operativo_metodo
        CHECK (metodo IN ('EFECTIVO', 'QR', 'TARJETA', 'TRANSFERENCIA', 'OTRO')),
    CONSTRAINT ck_pago_operativo_estado
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'ANULADO'))
);

COMMENT ON TABLE pago_operativo IS 'Pago operativo asociado a una estancia; no representa una pasarela bancaria real.';

-- -----------------------------------------------------------------------------
-- 13. BLOQUEO_ESPACIO
-- Estados definidos por el modelo:
-- PROGRAMADO, ACTIVO, FINALIZADO, CANCELADO.
-- -----------------------------------------------------------------------------
CREATE TABLE bloqueo_espacio (
    bloqueo_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    espacio_id     BIGINT       NOT NULL,
    fecha_inicio   TIMESTAMPTZ  NOT NULL,
    fecha_fin      TIMESTAMPTZ,
    motivo         VARCHAR(200) NOT NULL,
    estado         VARCHAR(20)  NOT NULL,
    created_by     BIGINT       NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_bloqueo_espacio PRIMARY KEY (bloqueo_id),
    CONSTRAINT fk_bloqueo_espacio_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacio (espacio_id),
    CONSTRAINT fk_bloqueo_espacio_usuario
        FOREIGN KEY (created_by)
        REFERENCES usuario (usuario_id),
    CONSTRAINT ck_bloqueo_espacio_intervalo
        CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio),
    CONSTRAINT ck_bloqueo_espacio_estado
        CHECK (estado IN ('PROGRAMADO', 'ACTIVO', 'FINALIZADO', 'CANCELADO'))
);

COMMENT ON TABLE bloqueo_espacio IS 'Periodo durante el cual un espacio no debe estar disponible para uso normal.';

-- -----------------------------------------------------------------------------
-- 14. INCIDENCIA
-- Estados definidos por el modelo:
-- ABIERTA, EN_REVISION, RESUELTA, CERRADA.
-- El documento no fija un catalogo exhaustivo de tipo; por ello se protege como
-- texto obligatorio no vacio en vez de inventar un listado cerrado.
-- -----------------------------------------------------------------------------
CREATE TABLE incidencia (
    incidencia_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    espacio_id      BIGINT,
    estancia_id     BIGINT,
    tipo            VARCHAR(40) NOT NULL,
    descripcion     TEXT        NOT NULL,
    estado          VARCHAR(20) NOT NULL,
    created_by      BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    resolved_at     TIMESTAMPTZ,

    CONSTRAINT pk_incidencia PRIMARY KEY (incidencia_id),
    CONSTRAINT fk_incidencia_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacio (espacio_id),
    CONSTRAINT fk_incidencia_estancia
        FOREIGN KEY (estancia_id)
        REFERENCES estancia (estancia_id),
    CONSTRAINT fk_incidencia_usuario
        FOREIGN KEY (created_by)
        REFERENCES usuario (usuario_id),
    CONSTRAINT ck_incidencia_tipo_no_vacio
        CHECK (BTRIM(tipo) <> ''),
    CONSTRAINT ck_incidencia_estado
        CHECK (estado IN ('ABIERTA', 'EN_REVISION', 'RESUELTA', 'CERRADA')),
    CONSTRAINT ck_incidencia_resolved_at
        CHECK (resolved_at IS NULL OR resolved_at >= created_at)
);

COMMENT ON TABLE incidencia IS 'Problema o evento excepcional que debe ser atendido y trazado.';

-- -----------------------------------------------------------------------------
-- 15. HISTORIAL_ESTADO
-- resource_type + resource_id forman una referencia logica polimorfica.
-- NO se define FK fisica para resource_id porque puede apuntar a distintos tipos
-- de recursos segun resource_type.
-- -----------------------------------------------------------------------------
CREATE TABLE historial_estado (
    historial_estado_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resource_type        VARCHAR(50) NOT NULL,
    resource_id          BIGINT      NOT NULL,
    estado_anterior      VARCHAR(30),
    estado_nuevo         VARCHAR(30) NOT NULL,
    changed_by           BIGINT      NOT NULL,
    changed_at           TIMESTAMPTZ NOT NULL,
    motivo               TEXT,

    CONSTRAINT pk_historial_estado PRIMARY KEY (historial_estado_id),
    CONSTRAINT fk_historial_estado_usuario
        FOREIGN KEY (changed_by)
        REFERENCES usuario (usuario_id)
);

COMMENT ON TABLE historial_estado IS 'Registro cronologico de cambios de estado de recursos del sistema.';

-- -----------------------------------------------------------------------------
-- 16. AUDITORIA
-- usuario_id puede ser NULL para procesos tecnicos.
-- resource_type + resource_id constituyen una referencia logica, no una FK fisica
-- tradicional.
-- -----------------------------------------------------------------------------
CREATE TABLE auditoria (
    auditoria_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT,
    accion          VARCHAR(60) NOT NULL,
    resource_type   VARCHAR(60) NOT NULL,
    resource_id     BIGINT,
    occurred_at     TIMESTAMPTZ NOT NULL,
    ip_address      VARCHAR(64),
    details         JSONB,

    CONSTRAINT pk_auditoria PRIMARY KEY (auditoria_id),
    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
);

COMMENT ON TABLE auditoria IS 'Eventos tecnicos o funcionales relevantes para trazabilidad.';

-- -----------------------------------------------------------------------------
-- 17. INDICES RECOMENDADOS PARA CLAVES FORANEAS Y CONSULTAS FRECUENTES
-- Estos indices no cambian el modelo logico; son una decision fisica de rendimiento.
-- PostgreSQL NO crea automaticamente indices para las columnas FK.
-- -----------------------------------------------------------------------------
CREATE INDEX ix_usuario_rol_usuario_id
    ON usuario_rol (usuario_id);
CREATE INDEX ix_usuario_rol_rol_id
    ON usuario_rol (rol_id);

CREATE INDEX ix_zona_estacionamiento_id
    ON zona (estacionamiento_id);

CREATE INDEX ix_espacio_zona_id
    ON espacio (zona_id);
CREATE INDEX ix_espacio_estado
    ON espacio (estado);

CREATE INDEX ix_vehiculo_cliente_id
    ON vehiculo (cliente_id);

CREATE INDEX ix_tarifa_estacionamiento_id
    ON tarifa (estacionamiento_id);

CREATE INDEX ix_reserva_vehiculo_id
    ON reserva (vehiculo_id);
CREATE INDEX ix_reserva_espacio_id
    ON reserva (espacio_id);
CREATE INDEX ix_reserva_intervalo
    ON reserva (espacio_id, fecha_inicio, fecha_fin);
CREATE INDEX ix_reserva_estado
    ON reserva (estado);

CREATE INDEX ix_estancia_vehiculo_id
    ON estancia (vehiculo_id);
CREATE INDEX ix_estancia_espacio_id
    ON estancia (espacio_id);
CREATE INDEX ix_estancia_tarifa_id
    ON estancia (tarifa_id);
CREATE INDEX ix_estancia_estado
    ON estancia (estado);

CREATE INDEX ix_pago_operativo_estancia_id
    ON pago_operativo (estancia_id);

CREATE INDEX ix_bloqueo_espacio_espacio_id
    ON bloqueo_espacio (espacio_id);
CREATE INDEX ix_bloqueo_espacio_created_by
    ON bloqueo_espacio (created_by);
CREATE INDEX ix_bloqueo_espacio_intervalo
    ON bloqueo_espacio (espacio_id, fecha_inicio, fecha_fin);

CREATE INDEX ix_incidencia_espacio_id
    ON incidencia (espacio_id);
CREATE INDEX ix_incidencia_estancia_id
    ON incidencia (estancia_id);
CREATE INDEX ix_incidencia_created_by
    ON incidencia (created_by);
CREATE INDEX ix_incidencia_estado
    ON incidencia (estado);

CREATE INDEX ix_historial_estado_resource
    ON historial_estado (resource_type, resource_id, changed_at);
CREATE INDEX ix_historial_estado_changed_by
    ON historial_estado (changed_by);

CREATE INDEX ix_auditoria_usuario_id
    ON auditoria (usuario_id);
CREATE INDEX ix_auditoria_resource
    ON auditoria (resource_type, resource_id, occurred_at);

-- -----------------------------------------------------------------------------
-- 18. VERIFICACION RAPIDA: listar tablas creadas dentro del schema parkflow
-- -----------------------------------------------------------------------------
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'parkflow'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- FIN DEL SCRIPT
